# GitHub Action para gerar o gráfico de contribuições da snake

name: Generate Snake

on:
  # Roda a cada 6 horas
  schedule:
    - cron: "0 */6 * * *"
  # Permite que você rode essa action manualmente pela aba Actions do GitHub
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----> AQUI ESTÁ A CORREÇÃO! <----
      # Adicionamos este passo para criar a pasta 'dist' antes de usá-la.
      - name: Create output directory
        run: mkdir -p dist

      - name: Generate snake animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # O caminho de saída continua o mesmo, mas agora a pasta vai existir.
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push generated file to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
